devices = [
        {
            "id": "atlas",
            "name": "Atlas",
            "role": "Main Server",
            "status": "online",
            "cpu": None,
            "memory": None,
            "disk": None,
            "uptime": None,
        },
        {
            "id": "apollo",
            "name": "Apollo",
            "role": "Primary Workstation",
            "status": "online",
            "cpu": None,
            "memory": None,
            "disk": None,
            "uptime": None,
        },
        {
            "id": "hyperion",
            "name": "Hyperion",
            "role": "Home PC",
            "status": "online",
            "cpu": None,
            "memory": None,
            "disk": None,
            "uptime": None,
        },
    ]